/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 06-nov.-2019 11:32:15 a. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS Area CASCADE
;

DROP TABLE IF EXISTS Ciclo_propedeutico CASCADE
;

DROP TABLE IF EXISTS Institucion_educativa CASCADE
;

DROP TABLE IF EXISTS Facultad CASCADE
;

DROP TABLE IF EXISTS Otras_herramientas CASCADE
;

DROP TABLE IF EXISTS Persona CASCADE
;

DROP TABLE IF EXISTS ResultadoCompetenciasTIC CASCADE
;

DROP TABLE IF EXISTS ResultadoHerramientas CASCADE
;

DROP TABLE IF EXISTS Usuario CASCADE
;

DROP TABLE IF EXISTS Administrador CASCADE
;
/* Create Tables */

CREATE TABLE Area
(
	`k_id` DECIMAL(2,0) NOT NULL,
	`n_nombre` VARCHAR(50) NOT NULL,
	`n_tipo` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Area` PRIMARY KEY (`k_id` ASC)
)

;

CREATE TABLE Ciclo_propedeutico
(
	`k_id` DECIMAL(2,0) NOT NULL COMMENT 'Identificador unico que cada uno de los 3 ciclos propedeuticos.',
	`n_nombre` VARCHAR(30) NOT NULL,
	CONSTRAINT `PK_Ciclo_propedeutico` PRIMARY KEY (`k_id` ASC)
)

;

CREATE TABLE Institucion_educativa
(
	`k_id` DECIMAL(2,0) NOT NULL,
	`n_nombre` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Institucion_educativa` PRIMARY KEY (`k_id` ASC)
)

;

CREATE TABLE Facultad
(
	`k_id` DECIMAL(2,0) NOT NULL,
	`n_nombre` VARCHAR(50) NOT NULL,
	`fk_id_institucion` DECIMAL(2,0) NULL,
	CONSTRAINT `PK_Facultad` PRIMARY KEY (`k_id` ASC)
)

;

CREATE TABLE Otras_herramientas
(
	`k_id` DECIMAL(2,0) NOT NULL,
	`v_valor` VARCHAR(20) NOT NULL,
	`v_tipo` VARCHAR(50) NOT NULL,
	`k_cedula_resultados` VARCHAR(11) NULL,
	CONSTRAINT `PK_Otras_herramientas` PRIMARY KEY (`k_id` ASC)
)

;

CREATE TABLE Persona
(
	`k_cedula` VARCHAR(11) NOT NULL,
	`n_nombre` VARCHAR(50) NULL,
	`n_apellido` VARCHAR(50) NULL,
	`n_imagen` VARCHAR(50) NULL,
	`o_genero` VARCHAR(1) NULL,
	`n_email` VARCHAR(50) NULL,
	`n_ha_recibido_formacion` VARCHAR(10) NULL,
	`n_año` VARCHAR(10) NULL,
	`fk_id_institucion` DECIMAL(2,0) NULL,
	`k_id_area` DECIMAL(2,0) NULL,
	`k_id_ciclo` DECIMAL(2,0) NULL,
	`k_id_facultad` DECIMAL(2,0) NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`k_cedula` ASC)
)

;

CREATE TABLE ResultadoCompetenciasTIC
(
	`v_tecM1` DECIMAL(2,0) NOT NULL,
	`v_tecM2` DECIMAL(2,0) NOT NULL,
	`v_tecM3` DECIMAL(2,0) NOT NULL,
	`v_pedM1` DECIMAL(2,0) NOT NULL,
	`v_pedM2` DECIMAL(2,0) NOT NULL,
	`v_pedM3` DECIMAL(2,0) NOT NULL,
	`v_comM1` DECIMAL(2,0) NOT NULL,
	`v_comM2` DECIMAL(2,0) NOT NULL,
	`v_comM3` DECIMAL(2,0) NOT NULL,
	`v_gesM1` DECIMAL(2,0) NOT NULL,
	`v_gesM2` DECIMAL(2,0) NOT NULL,
	`v_gesM3` DECIMAL(2,0) NOT NULL,
	`v_invM1` DECIMAL(2,0) NOT NULL,
	`v_invM2` DECIMAL(2,0) NOT NULL,
	`v_invM3` DECIMAL(2,0) NOT NULL,
	`k_cedula` VARCHAR(11) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`k_cedula` ASC)
)

;

CREATE TABLE ResultadoHerramientas
(
	`v_trabajoColaborativo` VARCHAR(150) NOT NULL,
	`v_OVA` VARCHAR(100) NOT NULL,
	`v_video` VARCHAR(100) NOT NULL,
	`v_audio` VARCHAR(50) NOT NULL,
	`v_texto_imagenes` VARCHAR(100) NOT NULL,
	`v_presentacion` VARCHAR(60) NOT NULL,
	`v_videoConferencia` VARCHAR(100) NOT NULL,
	`v_comunidades` VARCHAR(150) NOT NULL,
	`v_bibliografico` VARCHAR(50) NOT NULL,
	`v_mapas` VARCHAR(50) NOT NULL,
	`v_lineas` VARCHAR(55) NOT NULL,
	`v_actividades` VARCHAR(50) NOT NULL,
	`v_LMS` VARCHAR(60) NOT NULL,
	`v_comunicacion_gestion` VARCHAR(50) NOT NULL,
	`v_estadistica` VARCHAR(25) NOT NULL,
	`k_cedula` VARCHAR(11) NOT NULL,
	CONSTRAINT `PK_ResultadoHerramientas` PRIMARY KEY (`k_cedula` ASC)
)

;

CREATE TABLE Usuario
(
	`k_id` DECIMAL(8,0) NOT NULL,
	`n_usuario` VARCHAR(30) NOT NULL,
	`n_clave` VARCHAR(100) NOT NULL,
	`k_cedula_persona` VARCHAR(11) NULL,
	CONSTRAINT `PK_Usuario` PRIMARY KEY (`k_id` ASC)
)

;

CREATE TABLE Administrador
(
	`k_id` DECIMAL(8,0) NOT NULL,
	`n_usuario` VARCHAR(30) NOT NULL,
	`n_clave` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_Administrador` PRIMARY KEY (`k_id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Otras_herramientas 
 ADD INDEX `IXFK_Otras_herramientas_ResultadoHerramientas` (`k_cedula_resultados` ASC)
;

ALTER TABLE Persona 
 ADD INDEX `IXFK_Persona_Area` (`k_id_area` ASC)
;

ALTER TABLE Persona 
 ADD INDEX `IXFK_Persona_Ciclo_propedeutico` (`k_id_ciclo` ASC)
;

ALTER TABLE Persona 
 ADD INDEX `IXFK_Persona_Institucion_educativa` (`fk_id_institucion` ASC)
;

ALTER TABLE Persona 
 ADD INDEX `IXFK_Persona_Facultad` (`k_id_facultad` ASC)
;

ALTER TABLE ResultadoCompetenciasTIC 
 ADD INDEX `IXFK_ResultadoCompetenciasTIC_Persona` (`k_cedula` ASC)
;

ALTER TABLE ResultadoHerramientas 
 ADD INDEX `IXFK_ResultadoHerramientas_Persona` (`k_cedula` ASC)
;

/*ALTER TABLE Usuario 
 ADD INDEX `IXFK_Usuario_Persona` (`k_cedula_persona` ASC)
;
*/
/* Create Foreign Key Constraints */

ALTER TABLE Otras_herramientas 
 ADD CONSTRAINT `FK_Otras_herramientas_ResultadoHerramientas`
	FOREIGN KEY (`k_cedula_resultados`) REFERENCES ResultadoHerramientas (`k_cedula`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Persona 
 ADD CONSTRAINT `FK_Persona_Area`
	FOREIGN KEY (`k_id_area`) REFERENCES Area (`k_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Persona 
 ADD CONSTRAINT `FK_Persona_Ciclo_propedeutico`
	FOREIGN KEY (`k_id_ciclo`) REFERENCES Ciclo_propedeutico (`k_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Persona 
 ADD CONSTRAINT `FK_Persona_Institucion_educativa`
	FOREIGN KEY (`fk_id_institucion`) REFERENCES Institucion_educativa (`k_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Persona 
 ADD CONSTRAINT `FK_Persona_Facultad`
	FOREIGN KEY (`k_id_facultad`) REFERENCES Facultad (`k_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE ResultadoCompetenciasTIC 
 ADD CONSTRAINT `FK_ResultadoCompetenciasTIC_Persona`
	FOREIGN KEY (`k_cedula`) REFERENCES Persona (`k_cedula`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE ResultadoHerramientas 
 ADD CONSTRAINT `FK_ResultadoHerramientas_Persona`
	FOREIGN KEY (`k_cedula`) REFERENCES Persona (`k_cedula`) ON DELETE Restrict ON UPDATE Restrict
;

/*ALTER TABLE Usuario 
 ADD CONSTRAINT `FK_Usuario_Persona`
	FOREIGN KEY (`k_cedula_persona`) REFERENCES Persona (`k_cedula`) ON DELETE Restrict ON UPDATE Restrict
;*/

SET FOREIGN_KEY_CHECKS=1 
;
/*ALTER TABLE `persona` ADD `n_apellido` VARCHAR(50) NULL AFTER `n_nombre`, ADD `n_imagen` VARCHAR(50) NULL AFTER `n_apellido`;*/
INSERT INTO institucion_educativa (k_id, n_nombre) VALUES (0, 'Universidad Distrital');
INSERT INTO institucion_educativa (k_id, n_nombre) VALUES (1, 'Universidad Nacional');
INSERT INTO ciclo_propedeutico (k_id, n_nombre) VALUES (0, 'Profesional Universitario');
INSERT INTO ciclo_propedeutico (k_id, n_nombre) VALUES (1, 'Tecnológo');
INSERT INTO area (k_id, n_nombre, n_tipo) VALUES (0, 'Matemáticas', 'Teórica');
INSERT INTO area (k_id, n_nombre, n_tipo) VALUES (1, 'Física', 'Teórico-Práctica');
INSERT INTO area (k_id, n_nombre, n_tipo) VALUES (2, 'Artes', 'Práctica');

INSERT INTO facultad (k_id, n_nombre, fk_id_institucion) VALUES (0, 'Ingeniería', 0);
INSERT INTO facultad (k_id, n_nombre, fk_id_institucion) VALUES (1, 'Macarena', 0);
INSERT INTO facultad (k_id, n_nombre, fk_id_institucion) VALUES (2, 'Ciencias', 1);

/*INSERT INTO persona (k_cedula, n_nombre, n_apellido, n_imagen,  o_genero, n_email, fk_id_institucion, k_id_area, k_id_ciclo) VALUES (1023958895, 'Rin', 'Algo', "rin.jpg", 'Femenino',"nosoymago@gmail.com", 1,0,0)
ALTER TABLE `resultadoherramientas` ADD `v_video` VARCHAR(100) NOT NULL AFTER `v_OVA`;